import { PacketDef, def } from "../registry/packet-def";
import { fields } from "../schema/infer";
import { PacketSchema } from "../schema/types";

const NICK = fields([{ name: "nickname", type: "string" }]);

export const AcceptFriendRequest = def({ id: -1926185291, name: "AcceptFriendRequest", direction: "c2s", schema: NICK });
export const AcknowledgeNewFriend = def({ id: 1286861380, name: "AcknowledgeNewFriend", direction: "c2s", schema: NICK });
export const AcknowledgeNewFriendRequest = def({ id: -1041660861, name: "AcknowledgeNewFriendRequest", direction: "c2s", schema: NICK });
export const AlreadyFriends = def({ id: -2089008699, name: "AlreadyFriends", direction: "s2c", schema: NICK });
export const CancelFriendRequest = def({ id: 84050355, name: "CancelFriendRequest", direction: "c2s", schema: NICK });
export const CheckUserExistsForFriend = def({ id: 126880779, name: "CheckUserExistsForFriend", direction: "c2s", schema: NICK });
export const DeclineAllFriendRequests = def({ id: -1590185083, name: "DeclineAllFriendRequests", direction: "c2s", schema: [] });
export const DeclineFriendRequest = def({ id: -1588006900, name: "DeclineFriendRequest", direction: "c2s", schema: NICK });
export const FriendRemoved = def({ id: 1716773193, name: "FriendRemoved", direction: "s2c", schema: NICK });
export const FriendRequestAccepted = def({ id: -139645601, name: "FriendRequestAccepted", direction: "s2c", schema: NICK });
export const FriendRequestAlreadySent = def({ id: 2064692768, name: "FriendRequestAlreadySent", direction: "s2c", schema: NICK });
export const FriendRequestCanceledOrDeclined = def({ id: 614714702, name: "FriendRequestCanceledOrDeclined", direction: "s2c", schema: NICK });
export const FriendRequestDeclined = def({ id: -1885167992, name: "FriendRequestDeclined", direction: "s2c", schema: NICK });
export const FriendRequestSent = def({ id: -1241704092, name: "FriendRequestSent", direction: "s2c", schema: NICK });
export const FriendsList = def({ id: 1422563374, name: "FriendsList", direction: "s2c", schema: [{ name: "acceptedFriends", type: "nullableStringArray" }, { name: "newAcceptedFriends", type: "nullableStringArray" }, { name: "incomingRequests", type: "nullableStringArray" }, { name: "newIncomingRequests", type: "nullableStringArray" }, { name: "outgoingRequests", type: "nullableStringArray" }] });
export const IncomingFriendRequestExists = def({ id: -1258754138, name: "IncomingFriendRequestExists", direction: "s2c", schema: NICK });
export const LoadFriends = def({ id: -731115522, name: "LoadFriends", direction: "s2c", schema: [{ name: "unknown", type: "bool" }] });
export const NewFriendRequest = def({ id: 553380510, name: "NewFriendRequest", direction: "s2c", schema: NICK });
export const RemoveFriend = def({ id: -221757454, name: "RemoveFriend", direction: "c2s", schema: NICK });
export const UserExistsForFriend = def({ id: -707501253, name: "UserExistsForFriend", direction: "s2c", schema: [] });
export const UserInvalidForFriend = def({ id: -1490761936, name: "UserInvalidForFriend", direction: "s2c", schema: [] });
export const SendFriendRequest = def({ id: -1457773660, name: "SendFriendRequest", direction: "c2s", schema: NICK });
export const RequestFriendsListWindow = def({ id: 1441234714, name: "RequestFriendsListWindow", direction: "c2s", schema: [] });
export const ShowFriendsListWindow = def({ id: -437587751, name: "ShowFriendsListWindow", direction: "s2c", schema: [] });
